train:
	python train.py --debug --data_path /data/trial_en/trial_en/en/ --file_label_name en_ENEW_LIST.json --file_data_name en-trial-wiki-20190121-cirrussearch-content.json.gz

run_abci:
	qsub -g gcc50441 ./abci.sh