name: Test
debug: True
exp_name: bert test code
data:
  data_path: /data/
  file_label_name: en_ENEW_LIST.json
  file_data_name: en-trial-wiki-20190121-cirrussearch-content.json.gz
  batch_size: 16
  num_workers: 4
train:
  epoch: 20
optim:
  learning_rate: 0.001