name: Test
debug: False
exp_name: bert entire sentence
data:
  data_type: entire
  data_path: /data/
  file_label_name: en_ENEW_LIST.json
  file_data_name: en-trial-wiki-20190121-cirrussearch-content.json.gz
  batch_size: 16
  num_workers: 1 
train:
  epoch: 20
optim:
  learning_rate: 0.001