FROM nvcr.io/nvidia/pytorch:20.11-py3

RUN pip3 install \
    Janome==0.4.1 \
    subword-nmt==0.3.7 \
    hydra-core==1.0 \
    transformers==3.0.1 \
    tensorboard==2.4.1 \
    tensorboardX==2.2 \
    scikit-learn==0.24.1 \
    autopep8 \
    flake8 